name: Auto Merge PR

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

permissions:
  contents: write  # Untuk merge otomatis
  pull-requests: write  # Untuk memberi komentar di PR

jobs:
  check-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          json: true

      - name: Check if changes are valid
        id: validate-changes
        run: |
          VALID=true
          for file in $(jq -r '.[]' <<< '${{ steps.changed-files.outputs.all_changed_files }}'); do
            if [[ ! "$file" =~ ^nama_pelaku/.*\.txt$ ]]; then
              echo "❌ Pull Request mengandung file di luar 'nama_pelaku/' atau bukan .txt: $file"
              VALID=false
            fi
          done
          echo "VALID=$VALID" >> $GITHUB_ENV

      - name: Check for merge conflicts
        id: check-conflict
        run: |
          CONFLICT=false
          if git ls-files -u | grep -q .; then
            echo "❌ PR memiliki konflik merge"
            CONFLICT=true
          fi
          echo "CONFLICT=$CONFLICT" >> $GITHUB_ENV

      - name: Comment on PR if invalid
        if: env.VALID == 'false' || env.CONFLICT == 'true'
        run: |
          MESSAGE="🚨 PR tidak dapat di-merge otomatis.\n"
          if [ "$VALID" == "false" ]; then
            MESSAGE+="❌ PR mengandung file di luar 'nama_pelaku/' atau bukan .txt.\n"
          fi
          if [ "$CONFLICT" == "true" ]; then
            MESSAGE+="❌ PR memiliki konflik merge.\n"
          fi
          gh pr comment "$PR_NUMBER" --body "$MESSAGE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge PR
        if: env.VALID == 'true' && env.CONFLICT == 'false'
        run: gh pr merge "$PR_NUMBER" --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
