name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Check modified files
        id: check_files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/master)
          echo "Changed files: $CHANGED_FILES"
          
          INVALID_FILES=$(echo "$CHANGED_FILES" | grep -v '^nama_pelaku/.*\.txt$' || true)
          
          if [[ -n "$INVALID_FILES" ]]; then
            echo "Invalid files detected: $INVALID_FILES"
            exit 1
          fi

      - name: Check for merge conflicts
        id: check_conflict
        run: |
          git fetch origin master
          if git merge-base --is-ancestor origin/master HEAD; then
            echo "No conflicts detected."
          else
            echo "Merge conflicts detected!"
            exit 1
          fi

      - name: Merge Pull Request
        run: gh pr merge "$PR_NUMBER" --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
