name: Auto-merge PRs
on:
  pull_request:
    types: [opened, synchronize]
    
permissions:
  contents: write
  pull-requests: write
  issues: write
      
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: Contributors.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate changes
        id: validate
        run: |
          if [[ "${{ steps.changed-files.outputs.all_changed_files }}" == "Contributors.md" ]]; then
            echo "only_contributors=true" >> $GITHUB_ENV
          else
            echo "only_contributors=false" >> $GITHUB_ENV
          fi
          if [[ ${{ github.event.pull_request.additions }} -le 2 && ${{ github.event.pull_request.deletions }} -le 1 ]]; then
            echo "valid_changes=true" >> $GITHUB_ENV
          else
            echo "valid_changes=false" >> $GITHUB_ENV
          fi

      - name: Merge PR
        if: env.only_contributors == 'true' && env.valid_changes == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: "squash"
            });
            // Add your celebration comment logic here
